config/routes.rb
Rails.application.routes.draw do
  get 'greetings/hello'

  get 'greetings/goodbye'

  get 'greetings/Hello'

  get 'greetings/GOodbye'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def hello
  	@time= Time.now
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/views/greetings/goodbye.html.erb
<h1>Greetings#goodbye</h1>
<p>You know what GOOD BYE RIGHT BECAUSE I NEVER LIKED YOU!!!!!. If you changed your mind because you want to get your opportunity you have really waited for you can come back and lets say <%= link_to "hello", greetings_hello_path%> </p>

app/views/greetings/hello.html.erb
<h1>Greetings#hello</h1>
<p>I'm so sorry that I didnt introduce myself.I am Andrews and if you don't like me because I did not introduce myself then <%=link_to "bye bye",greetings_goodbye_path%><br />
<%=@time%>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>